packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.83.0
  '@trpc/client': ^11.4.3
  '@trpc/react-query': ^11.4.3
  '@trpc/server': ^11.4.3
  eslint: ^9.30.1
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^3.25.76

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.23
    '@types/react-dom': ^18.3.7
