packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.77.1
  '@trpc/client': ^11.1.2
  '@trpc/react-query': ^11.1.2
  '@trpc/server': ^11.1.2
  eslint: ^9.27.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^3.25.28

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.22
    '@types/react-dom': ^18.3.7
