packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.81.2
  '@trpc/client': ^11.4.2
  '@trpc/react-query': ^11.4.2
  '@trpc/server': ^11.4.2
  eslint: ^9.29.0
  prettier: ^3.6.1
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^3.25.67

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.23
    '@types/react-dom': ^18.3.7
