packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.66.11
  '@trpc/client': ^11.0.0-rc.818
  '@trpc/react-query': ^11.0.0-rc.818
  '@trpc/server': ^11.0.0-rc.818
  eslint: ^9.21.0
  prettier: ^3.5.2
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  zod: ^3.24.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.18
    '@types/react-dom': ^18.3.5
