packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.85.2
  '@trpc/client': ^11.4.4
  '@trpc/react-query': ^11.4.4
  '@trpc/server': ^11.4.4
  eslint: ^9.33.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.9.2
  zod: ^3.25.76

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.23
    '@types/react-dom': ^18.3.7
