packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.74.3
  '@trpc/client': ^11.1.0
  '@trpc/react-query': ^11.1.0
  '@trpc/server': ^11.1.0
  eslint: ^9.24.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^3.24.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.20
    '@types/react-dom': ^18.3.6
