packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.80.6
  '@trpc/client': ^11.3.1
  '@trpc/react-query': ^11.3.1
  '@trpc/server': ^11.3.1
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  zod: ^3.25.61

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.23
    '@types/react-dom': ^18.3.7
